CREATE TABLE IF NOT EXISTS admin (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS student (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    dni CHAR(8),
    firstName VARCHAR(255),
    lastName VARCHAR(255),
    promotion VARCHAR(255),
    fecha date DEFAULT CURRENT_TIMESTAMP
);
