apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: jesus-luyo
type: Opaque
stringData:
  url: "r2dbc:postgresql://ep-icy-tree-a4b64iqg-pooler.us-east-1.aws.neon.tech:5432/assistance?sslmode=require"
  username: "neondb_owner"
  password: "npg_RitqK8seGb5f"
