apiVersion: apps/v1
kind: Deployment
metadata:
  name: vg-ms-assistance
  namespace: jesus-luyo
  labels:
    app: vg-ms-assistance # Debe coincidir con Service selector
spec:
  replicas: 2 # Número de pods
  selector:
    matchLabels:
      app: vg-ms-assistance
  template:
    metadata:
      labels:
        app: vg-ms-assistance
    spec:
      containers:
        - name: app
          image: vidalluyo0/vg-ms-assistance:1.0 # Cambiar versión aquí
          imagePullPolicy: Always
          ports:
            - containerPort: 9087
          env:
            - name: SERVER_PORT
              value: "9087"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: MS_INSTITUTION
              value: "http://vg-ms-institution:9080"
            - name: MS_STUDENT
              value: "http://vg-ms-students:9081"
          resources:
            requests: # Mínimo garantizado
              memory: "512Mi"
              cpu: "250m"
            limits: # Máximo permitido
              memory: "1Gi"
              cpu: "500m"
