apiVersion: apps/v1
kind: Deployment
metadata:
  name: vg-ms-students
  namespace: jesus-luyo
  labels:
    app: vg-ms-students  # Debe coincidir con Service selector
spec:
  replicas: 2  # Número de pods
  selector:
    matchLabels:
      app: vg-ms-students
  template:
    metadata:
      labels:
        app: vg-ms-students
    spec:
      containers:
      - name: app
        image: vidalluyo0/vg-ms-students:1.0  # Cambiar versión aquí
        imagePullPolicy: Always
        ports:
        - containerPort: 9081
        env:
        - name: SERVER_PORT
          value: "9081"
        resources:
          requests:  # Mínimo garantizado
            memory: "512Mi"
            cpu: "250m"
          limits:  # Máximo permitido
            memory: "1Gi"
            cpu: "500m"
