apiVersion: v1
kind: Service
metadata:
  name: vg-ms-assistance
  namespace: jesus-luyo
  labels:
    app: vg-ms-assistance
spec:
  type: NodePort  # Expuesto externamente
  selector:
    app: vg-ms-assistance  # Conecta con Deployment
  ports:
  - protocol: TCP
    port: 9087
    targetPort: 9087
    nodePort: 30087  # Puerto externo (30000-32767)
