apiVersion: v1
kind: Service
metadata:
  name: vg-ms-institution
  namespace: jesus-luyo
  labels:
    app: vg-ms-institution
spec:
  type: ClusterIP  # Solo interno
  selector:
    app: vg-ms-institution  # Conecta con Deployment
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
