apiVersion: v1
kind: Service
metadata:
  name: vg-ms-students
  namespace: jesus-luyo
  labels:
    app: vg-ms-students
spec:
  type: ClusterIP  # Solo interno
  selector:
    app: vg-ms-students  # Conecta con Deployment
  ports:
  - protocol: TCP
    port: 9081
    targetPort: 9081
