apiVersion: v1
kind: Service
metadata:
  name: vg-frontend
  namespace: jesus-luyo
  labels:
    app: vg-frontend
spec:
  type: NodePort
  selector:
    app: vg-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080  # Puerto externo para acceder al frontend
